### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'`

### ISSUE THREAD

**Issue by arkhandir** [Galarius/pinotate#4]
Thank you for the script. It works fine for a few books, then I get the following error:

`Traceback (most recent call last):
  File "/Users/***/pinotate-0.3/pinotate.py", line 44, in <module>
    main(args)
  File "/Users/***/pinotate-0.3/pinotate.py", line 30, in main
    worker.export_all(args)
  File "/Users/***/pinotate-0.3/core/worker.py", line 44, in export_all
    self.__export(title, args.out, args.headings, args.sort)
  File "/Users/***/pinotate-0.3/core/worker.py", line 51, in __export
    highlights = self.highlights(asset_id)
  File "/Users/***/pinotate-0.3/core/worker.py", line 37, in highlights
    return self.dispatcher.get_highlights(self.ann_db, asset_id)
  File "/Users/***/pinotate-0.3/core/db.py", line 141, in get_highlights
    chapter = int(location.split('[')[0].split('/')[2].replace(',', ''))
AttributeError: 'NoneType' object has no attribute 'split'

I’d would be happy if this could be fixed, the script seems to be the last resort to export hightlights from Apple Books.

Thank you!

**Comment by Galarius** [comment]
@arkhandir,thank you for reporting this issue!

**Comment by Galarius** [comment]
@arkhandir, the problem should be resolved in version [0.3.1](https://github.com/Galarius/pinotate/releases/tag/0.3.1). Please feel free to reopen the issue if it persists.

**Comment by arkhandir** [comment]
Thank you for fixing it. Your tool fills a gap left by Apple.
